default:
  random_seed: 27

datamodule:
  data_dir: "/media/youngwon/Neo/NeoChoi/Dataset"
  batch_size: 32

model:
  # model_name : "DNN"
  model_name: "CNN"
  drop_prob : 0.5

train:
  model_save_dir: "/media/youngwon/Neo/NeoChoi/TIL/Pytorch-DL/Classifiers/pt_MNIST/weights"
  max_epochs: 10

device: "cuda"