default:
  random_seed: 27

datamodule:
  data_dir: "/media/youngwon/Neo/NeoChoi/Dataset"
  batch_size: 32

model:
  model_name : "DNN"
  # model_name: "CNN"
  drop_prob : 0.5

train:
  logger_path: "./logger"
  max_epochs: 100
  earlystop_patience: 10

